name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore 
    - name: Test
      run: dotnet test Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-build --verbosity normal 