name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    - name: Restore dependencies
      run: dotnet restore -f "Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj"
    - name: Build
      run: dotnet build --no-restore -f "Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj"
    - name: Test
      run: dotnet test --no-build --verbosity normal -f "Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj"
